{
  "swagger": "2.0",
  "info": {
    "version": "2.30.0",
    "title": "DigiGrotesk API",
    "description": "Utilize esta documentação para aulixio ao uso da API do sistema!"
  },
  "host": "localhost:3000",
  "basePath": "/",
  "tags": [],
  "schemes": [
    "http"
  ],
  "securityDefinitions": {},
  "consumes": [],
  "produces": [],
  "paths": {
    "/user/": {
      "post": {
        "summary": "Criar usuário",
        "tags": [],
        "description": "Cria um usuário para que seja gerado os valores de key e token para autenticação à API",
        "parameters": [{
          "in": "body",
          "name": "email",
          "required": true,
          "example": "pedro@gmail.com",
          "description": "Email do usuário"
        },{
          "in": "body",
          "name": "password",
          "required": true,
          "example": "Senha123456",
          "description": "Senha do usuário"
        },{
          "in": "body",
          "name": "name",
          "required": false,
          "example": "Pedro",
          "description": "Nome do usuário"
        }],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "example": "Email do usuário cadastrado."
                },
                "x-key-api": {
                  "type": "string",
                  "example": "Key de autenticação do usuário para acessar a API."
                },
                "x-token-api": {
                  "type": "string",
                  "example": "Token de autenticação do usuário para acessar a API."
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar um email de usuário e senha para cadastro!"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}": {
      "put": {
        "tags": [],
        "summary": "Atualizar usuário",
        "description": "Atualiza o nome do usuário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },{
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": false,
            "example": "Pedro Henrique",
            "description": "Nome do usuário"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Usuário atualizado!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Não é possível atualizar a senha por essa rota de API!"
                }
              }
            }
          }
        }
      }
    },
    "/semester/": {
      "get": {
        "tags": [],
        "summary": "Retorna todos os períodos do usuário",
        "description": "Retorna todas as informações de todos os períodos do usuário",
        "parameters": [{
          "$ref": "#/parameters/x-key-api"
        },
          {
            "$ref": "#/parameters/x-token-api"
          }],
        "responses": {
          "200": {
            "description": "Retorna um objeto semesters contendo um array com todos os semesters daquele usuário",
            "schema": {
              "type": "object",
              "properties": {
                "semesters": {
                  "type": "array",
                  "example": [{}]
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [],
        "summary": "Criar período",
        "description": "Cria um período para o usuário",
        "parameters": [{
          "$ref": "#/parameters/x-key-api"
        },
          {
            "$ref": "#/parameters/x-token-api"
          },{
          "in": "body",
          "name": "name",
          "required": true,
          "description": "Nome do período para identificação",
            "example": "2020/01"
        },{
          "in": "body",
          "name": "startDate",
          "required": true,
            "description": "Data de início do período",
            "example": "2020-06-01"
        },{
          "in": "body",
          "name": "endDate",
          "required": true,
            "description": "Data de término do período",
            "example": "2020-12-31"
        }],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Período criado!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar um período para ser salvo!"
                }
              }
            }
          }
        }
      }
    },
    "/semester/{id}": {
      "get": {
        "tags": [],
        "summary": "Retorna um período em específico",
        "description": "Retorna o período correspondente ao id passado",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "Id do período a ser buscado",
            "example": "abcd1234"
          },{
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "description": "Retorna o objeto semester buscado",
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Nome do período"
                },
                "startDate": {
                  "type": "Date",
                  "example": "2020-06-01"
                },
                "endDate": {
                  "type": "Date",
                  "example": "2020-12-31"
                },
                "author": {
                  "type": "string",
                  "example": "IDAUTHOR"
                },
                "create": {
                  "type": "Date",
                  "example": "2020-06-05"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "semester": {
                  "type": "string",
                  "example": "É obrigatório passar um id na requisição para buscar um período específico!"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [],
        "summary": "Atualizar período",
        "description": "Permite atualizar nome, data de início e data de término do período",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },{
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": false,
            "example": "Novo nome",
            "description": "Nome a ser atualizado do período"
          },
          {
            "in": "body",
            "name": "startDate",
            "required": false,
            "description": "Data de início a ser atualizada",
            "example": "2020-06-10"
          },
          {
            "in": "body",
            "name": "endDate",
            "required": false,
            "description": "Data de término a ser atualizada",
            "example": "2020-06-10"
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Período atualizado!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar um id na requisição para buscar um período específico!"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [],
        "summary": "Deletar período",
        "description": "Deleta um período específico do usuário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },{
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Período excluido!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "O período selecionado para exclusão não existe!"
                }
              }
            }
          }
        }
      }
    },
    "/semester/{id}/subjects": {
      "get": {
        "summary" : "Retorna as disciplinas de um período específico",
        "description": "Retorna todas as disciplinas e suas informações do período especificado",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },{
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "description": "Retorna um objeto subjects contendo um array com todos os disciplina do semestre selecionado",
            "schema": {
              "type": "object",
              "properties": {
                "subjects": {
                  "type": "array",
                  "example": [{}]
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "array",
                  "example": "É obrigatório passar o id do período na requisição para buscar as disciplinas!"
                }
              }
            }
          }
        }
      }
    },
    "/semester/{id}/subjects/grade": {
      "get": {
        "tags": [],
        "summary": "Retorna as notas de cada disciplina de um período específico",
        "description": "Retorna as notas e a nota final de cada disciplina pertencente ao período especificado",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },{
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "semester": {
                  "type": "array",
                  "example": "Nome do período"
                },
                "subjects": {
                  "type": "array",
                  "example": [{
                    "name": "Nome da disciplina",
                    "finalGrade": "Nota final da disciplina",
                    "grades": []
                  }]
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar o id do período na requisição para buscar as notas!"
                }
              }
            }
          }
        }
      }
    },
    "/semester/{id}/info": {
      "get": {
        "summary": "Retorna as informações de um período específico",
        "tags": [],
        "description": "Retorna alem das informações do próprio périodo, retorna também as disciplinas e as tarefas, provas e aulas cadastradas nessas disciplinas",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Nome do período"
                },
                "start": {
                  "type": "Date",
                  "example": "2020-12-06"
                },
                "end": {
                  "type": "Date",
                  "example": "2020-12-06"
                },
                "subjects": {
                  "type": "array",
                  "example": [{
                    "name": "Nome da disciplina",
                    "exams": [],
                    "tasks": [],
                    "lessons": []
                  }]
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar um id na requisição para recuperar as informações do período!"
                }
              }
            }
          }
        }
      }
    },
    "/subject/": {
      "get": {
        "tags": [],
        "summary": "Retorna todas as disciplinas do usuário",
        "description": "Retorna todas as informações de todas as disciplinas do usuário",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "subjects": {
                  "type": "array",
                  "example":[
                    {
                      "name": "Nome da disciplina",
                      "teacher": "Nome do professor",
                      "school": "Noma da instituição de ensino",
                      "author": "id do usuário",
                      "semester": "id do período",
                      "start": "2020-06-01",
                      "end": "2020-12-31",
                      "create": "2020-06-05",
                      "finalGrade": 7.8,
                      "grades": [
                        {
                          "value": 8.0,
                          "weigth": 5
                        }
                      ]
                    }
                  ]}
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [],
        "summary": "Criar disciplina",
        "description": "Cria uma disciplina para o usuário",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": true,
            "example": "Construção de Software",
            "description": "Nome da disciplina"
          },
          {
            "in": "body",
            "name": "semester",
            "required": true,
            "example": "abcd1234",
            "description": "Id do período em que a disciplina pertence"
          },
          {
            "in": "body",
            "name": "start",
            "required": true,
            "example": "2020-06-01",
            "description": "Data de início da disciplina"
          },
          {
            "in": "body",
            "name": "end",
            "required": true,
            "example": "2020-12-01",
            "description": "Data de término da disciplina"
          },
          {
            "in": "body",
            "name": "teacher",
            "required": false,
            "example": "Walisson",
            "description": "Nome do professor que vai ministrar a disciplina"
          },
          {
            "in": "body",
            "name": "school",
            "required": false,
            "example": "UFG - INF",
            "description": "Nome da instituição de ensino"
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Disciplina criada!"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar uma disciplina para ser salva!"
                }
              }
            }
          }
        }
      }
    },
    "/subject/{id}": {
      "get": {
        "tags": [],
        "summary": "Retorna uma disciplina em específico",
        "description": "Retorna a disciplina correspondente ao id passado",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "subjects": {
                  "type": "array",
                  "example":
                    {
                      "name": "Nome da disciplina",
                      "teacher": "Nome do professor",
                      "school": "Noma da instituição de ensino",
                      "author": "id do usuário",
                      "semester": "id do período",
                      "start": "2020-06-01",
                      "end": "2020-12-31",
                      "create": "2020-06-05",
                      "finalGrade": 7.8,
                      "grades": [
                        {
                          "value": 8.0,
                          "weigth": 5
                        }
                      ]
                    }
                  }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar um id na requisição para buscar uma disciplina específica!"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [],
        "summary": "Atualizar disciplina",
        "description": "Permite atualizar nome, data de inicio e término, professor e instituição de ensino da disciplina",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": false,
            "example": "Construção de Software",
            "description": "Nome da disciplina"
          },
          {
            "in": "body",
            "name": "start",
            "required": false,
            "example": "2020-06-01",
            "description": "Data de início da disciplina"
          },
          {
            "in": "body",
            "name": "end",
            "required": false,
            "example": "2020-12-01",
            "description": "Data de término da disciplina"
          },
          {
            "in": "body",
            "name": "teacher",
            "required": false,
            "example": "Walisson",
            "description": "Nome do professor que vai ministrar a disciplina"
          },
          {
            "in": "body",
            "name": "school",
            "required": false,
            "example": "UFG - INF",
            "description": "Nome da instituição de ensino"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Disciplina atualizada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar um id na requisição para buscar uma disciplina específica!"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [],
        "summary": "Deletar disciplina",
        "description": "Deleta uma disciplina específica do usuário e todas as informações pertencentes a ela (tarefas, aulas, provas)",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Disciplina exlcuida!"
                }
              }
            }
          }
        }
      }
    },
    "/subject/{id}/exams": {
      "get": {
        "tags": [],
        "summary": "Retorna todas as provas da disciplina",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "exams": {
                  "type": "array",
                  "example":
                  [{
                    "name": "Nome de identificação da prova",
                    "subject": {
                      "id": "IDDISCIPLINA",
                      "author": "IDUSUARIO"
                    },
                    "theme": "Tema da prova",
                    "date": "2020-07-28",
                    "create": "2020-06-10"
                  }]
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar o id da disciplina na requisição para buscar as provas!"
                }
              }
            }
          }
        }
      }
    },
    "/subject/{id}/grade": {
      "put": {
        "tags": [],
        "summary": "Registrar notas da disciplina",
        "description": "Atualiza a nota da disciplina",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "grades",
            "required": true,
            "example": [{
              "value": 8.2,
              "weigth": 5
            }],
            "description": "Array de objetos que tem o atributo value (valor da nota) e weigth (peso da nota)"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Notas registradas!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar as notas para que sejam registradas na disciplina!"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [],
        "summary": "Retorna a nota da disciplina",
        "description": "Retorna a nota final da disciplina e as notas calculadas para gerar as notas finais",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Nome da disciplina"
                },
                "finalGrade": {
                  "type": "string",
                  "example": 7.8
                },
                "grades": {
                  "type": "array",
                  "example": [{
                    "value": 8.0,
                    "weigth": 5
                  }]
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar o id da disciplina na requisição para buscar as notas!"
                }
              }
            }
          }
        }
      }
    },
    "/subject/absence": {
      "post": {
        "tags": [],
        "summary": "Registrar ausência na disciplina",
        "description": "Registrar ausências ocorridas nas aulas da disciplina",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "subject",
            "required": true,
            "example": "abcd1234",
            "description": "Id da disciplina em que a ausência deve ser registrada"
          },
          {
            "in": "body",
            "name": "date",
            "required": true,
            "example": "2020-07-25",
            "description": "Data em que a ausência na aula ocorreu"
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Ausência registrada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar os dados da ausência na aula!"
                }
              }
            }
          }
        }
      }
    },
    "/subject/{id}/absence": {
      "get": {
        "tags": [],
        "summary": "Retorna todas as ausências da disciplina",
        "description": "Retorna todas as ausências de aulas registradas na disciplina",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "absences": {
                  "type": "array",
                  "example":
                  [{
                    "subject": {
                      "id": "IDDISCIPLINA",
                      "author": "IDUSUARIO"
                    },
                    "date": "2020-07-25",
                    "create": "2020-07/26"
                  }]
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      }
    },
    "/subject/{id}/absence/percent": {
      "get": {
        "tags": [],
        "summary": "Retorna a porcentagem de ausência da disciplina",
        "description": "Retorna a porcentagem de ausências de aula registrada na disciplina",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "attendance": {
                  "type": "string",
                  "example": "78 %"
                }
              }
            }
          },
          "404": {
            "schema": {
              "type": "object",
              "properties": {
                "attendance": {
                  "type": "string",
                  "example": "Disciplina não encontrada!"
                }
              }
            }
          }
        }
      }
    },
    "/exam/": {
      "get": {
        "tags": [],
        "summary": "Retorna todas as provas",
        "description": "Retorna todas as provas de todas as disciplinas cadastradas para o usuário",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "exams": {
                  "type": "array",
                  "example":
                  [{
                    "name": "Nome de identificação da prova",
                    "subject": {
                      "id": "IDDISCIPLINA",
                      "author": "IDUSUARIO"
                    },
                    "theme": "Tema da prova",
                    "date": "2020-07-28",
                    "create": "2020-06-10"
                  }]
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [],
        "summary": "Criar prova",
        "description": "Criar uma prova para uma disciplina em específico",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": true,
            "example": "Prova Um",
            "description": "Nome de identificação da prova"
          },
          {
            "in": "body",
            "name": "subject",
            "required": true,
            "example": "abcd1234",
            "description": "Id da disciplina em que a prova pertence"
          },
          {
            "in": "body",
            "name": "date",
            "required": true,
            "example": "2020-08-22",
            "description": "Data de realização da prova"
          },
          {
            "in": "body",
            "name": "theme",
            "required": false,
            "example": "Memória principal e barramentos",
            "description": "Conteúdo que vai ser abordado na prova"
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Prova criada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar uma prova para ser salva!"
                }
              }
            }
          }
        }
      }
    },
    "/exam/{id}": {
      "get": {
        "tags": [],
        "summary": "Retorna uma prova em específico",
        "description": "Retorna a prova correspondente ao id passado",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Prova Um"
                },
                "subject": {
                  "type": "object",
                  "example": {
                    "id": "IDDISCIPLINA",
                    "author": "IDUSUARIO"
                  }
                },
                "theme": {
                  "type": "string",
                  "example": "Memória principal e barramentos"
                },
                "date": {
                  "type": "date",
                  "example": "2020-08-22"
                },
                "create": {
                  "type": "date",
                  "example": "2020-08-26"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [],
        "summary": "Atualizar prova",
        "description": "Permite atualizar nome, data de realização e conteúdo abordado da prova",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": false,
            "example": "Prova Um",
            "description": "Nome de identificação da prova"
          },
          {
            "in": "body",
            "name": "date",
            "required": false,
            "example": "2020-08-22",
            "description": "Data de realização da prova"
          },
          {
            "in": "body",
            "name": "theme",
            "required": false,
            "example": "Memória principal e barramentos",
            "description": "Conteúdo que vai ser abordado na prova"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Prova atualizada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Não é possível atualizar a disciplina da prova!"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [],
        "summary": "Deletar prova",
        "description": "Deleta uma prova específica do usuário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Prova deletada!"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      }
    },
    "/task/": {
      "get": {
        "tags": [],
        "summary": "Retorna todas as tarefas",
        "description": "Retorna todas as tarefas de todas as disciplinas cadastradas para o usuário",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "tasks": {
                  "type": "array",
                  "example":
                  [{
                    "name": "Nome de identificação da tarefa",
                    "subject": {
                      "id": "IDDISCIPLINA",
                      "author": "IDUSUARIO"
                    },
                    "observation": "Lista de revisão - Se tiver dúvidas perguntar depois",
                    "deadline": "2020-07-28",
                    "realizedDate": "2020-07-29",
                    "realized": "true",
                    "create": "2020-06-10"
                  }]
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [],
        "summary": "Criar tarefa",
        "description": "Cria uma tarefa para uma disciplina em específico",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": true,
            "example": "Lista Um",
            "description": "Nome de identificação da tarefa"
          },
          {
            "in": "body",
            "name": "subject",
            "required": true,
            "example": "abcd1234",
            "description": "Id da disciplina em que a tarefa pertence"
          },
          {
            "in": "body",
            "name": "deadline",
            "required": true,
            "example": "2020-08-22",
            "description": "Data de entrega da tarefa"
          },
          {
            "in": "body",
            "name": "observation",
            "required": false,
            "example": "Se houver dúvia mandar por email",
            "description": "Uma observação pertinente à tarefa"
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Tarefa criada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar uma tarefa para ser salva!"
                }
              }
            }
          }
        }
      }
    },
    "/task/{id}": {
      "get": {
        "tags": [],
        "summary": "Retorna uma tarefa em específico",
        "description": "Retorna a tarefa correspondente ao id passado",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Lista Um"
                },
                "observation": {
                  "type": "string",
                  "example": "Se houver dúvia mandar por email"
                },
                "deadline": {
                  "type": "date",
                  "example": "2020-08-26"
                },
                "subject": {
                  "type": "object",
                  "example": {
                    "id": "IDDISCIPLINA",
                    "author": "IDUSUARIO"
                  }
                },
                "realized": {
                  "type": "boolean",
                  "example": true
                },
                "realizedDate": {
                  "type": "date",
                  "example": "2020-08-22"
                },
                "create": {
                  "type": "date",
                  "example": "2020-08-26"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [],
        "summary": "Atualizar tarefa",
        "description": "Permite atualizar o nome, observação e data de entrega da tarefa",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "name",
            "required": false,
            "example": "Lista Um",
            "description": "Nome de identificação da tarefa"
          },
          {
            "in": "body",
            "name": "deadline",
            "required": false,
            "example": "2020-08-22",
            "description": "Data de entrega da tarefa"
          },
          {
            "in": "body",
            "name": "observation",
            "required": false,
            "example": "Se houver dúvia mandar por email",
            "description": "Uma observação pertinente à tarefa"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Tarefa atualizada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Não é possível atualizar o author da tarefa!"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [],
        "summary": "Deletar tarefa",
        "description": "Deleta uma tarefa específica do usuário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Tarefa deletada!"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      }
    },
    "/task/{id}/realized": {
      "put": {
        "tags": [],
        "summary": "Registrar tarefa como entregue",
        "description": "Registra a tarefa como entregue, marcando assim a data com que a tarefa foi entregue",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Tarefa marcada como realizada!"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      }
    },
    "/lesson/": {
      "get": {
        "tags": [],
        "summary": "Retorna todas as aulas",
        "description": "Retorna todas as aulas de todas as disciplinas cadastradas para o usuário",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "lessons": {
                  "type": "array",
                  "example":
                  [{
                    "subject": {
                      "id": "IDDISCIPLINA",
                      "author": "IDUSUARIO"
                    },
                    "duration": 90,
                    "realizationDays": [{
                      "day": "mon",
                      "start": "18:50"
                    }],
                    "quantity": 64,
                    "create": "2020-07-15"
                  }]
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [],
        "summary": "Criar aula",
        "description": "Cria uma aula para uma disciplina em específico",
        "parameters": [
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "subject",
            "required": true,
            "example": "abcd12345",
            "description": "Id da disciplina em que a aula pertence"
          },
          {
            "in": "body",
            "name": "duration",
            "required": true,
            "example": 90,
            "description": "Tempo de duração da aula (em minutos)"
          },
          {
            "in": "body",
            "name": "realizationDays",
            "required": true,
            "example": [{
              "day": "mon",
              "start": "18:50"
            }],
            "description": "Um array de objetos contendo os dias de realização da aula. O objeto contem o atributo day, que representa qual dia da semana a aula vai ser realizada ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'], e o outro atributo é start que determina o horário de início da aula"
          }
        ],
        "responses": {
          "201": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Aula criada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "É obrigatório passar uma aula para ser salva!"
                }
              }
            }
          }
        }
      }
    },
    "/lesson/{id}": {
      "get": {
        "tags": [],
        "summary": "Retorna uma aula em específico",
        "description": "Retorna a aula correspondente ao id passado",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "subject": {
                  "type": "object",
                  "example": {
                    "id": "IDDISCIPLINA",
                    "author": "IDUSUARIO"
                  }
                },
                "duration": {
                  "type": "number",
                  "example": 90
                },
                "realizationDays": {
                  "type": "object",
                  "example": [{
                  "day": "mon",
                  "start": "18:50"
                }]},
                "quantity": {
                  "type": "number",
                  "example": 64
                },
                "create": {
                  "type": "date",
                  "example": "2020-07-10"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [],
        "summary": "Atualizar aula",
        "description": "Permite atualizar os dias de realização da aula e a duração",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          },
          {
            "in": "body",
            "name": "duration",
            "required": false,
            "example": 90,
            "description": "Tempo de duração da aula (em minutos)"
          },
          {
            "in": "body",
            "name": "realizationDays",
            "required": false,
            "example": [{
              "day": "mon",
              "start": "18:50"
            }],
            "description": "Um array de objetos contendo os dias de realização da aula. O objeto contem o atributo day, que representa qual dia da semana a aula vai ser realizada ['mon', 'tue', 'wed', 'thu', 'fri', 'sat'], e o outro atributo é start que determina o horário de início da aula"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Aula atualizada!"
                }
              }
            }
          },
          "400": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Não é possível atualizar a disciplina da aula!"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [],
        "summary": "Deletar aula",
        "description": "Deleta uma aula específica do usuário",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/x-key-api"
          },
          {
            "$ref": "#/parameters/x-token-api"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Aula deletada!"
                }
              }
            }
          },
          "500": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Erro interno do servidor"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {},
  "parameters": {
    "x-key-api": {
      "name": "x-key-api",
      "in": "header",
      "description": "API Key do seu usuário",
      "required": true,
      "type": "string"
    },
    "x-token-api": {
      "name": "x-token-api",
      "in": "header",
      "description": "API Key do seu usuário",
      "required": true,
      "type": "string"
    }
  }
}